import Footer from './Components/Footer'
import Header from './Components/Header'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className='container m-auto flex justify-center items-center flex-col'>{children}</main>
        <Footer />
      </body>

    </html>
  )
}
